version: '3'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=poc
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  users:
    container_name: "users"
    restart: always
    build:
      context: "."
      dockerfile: "users.Dockerfile"
    ports:
    - "8001:80"
    depends_on:
      - db
  orders:
    container_name: "orders"
    restart: always
    build:
      context: "."
      dockerfile: "orders.Dockerfile"
    ports:
      - "8000:80"
    depends_on:
      - db

volumes:
  db-data:
    driver: local